# Generated by Django 3.0.6 on 2020-05-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published',
            new_name='published_at',
        ),
    ]
